name: Pub Package Publish

on:
  push:
    tags:
      - '*.*.*'

env:
  flutter_version: '3.27.0'
  java_version: 17
  flutter_channel: 'stable'
  ruby_version: '2.7.5'
  release_version: '2.1.5'
  PACKAGE_DIR: l10n_mapper_generator

jobs:
  pub_package_publish:
    name: Test & Publish Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_DIR }}

    steps:
      - name: Get version from tag
        id: get_version
        working-directory: .
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby (Install and Cache bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true
          working-directory: ${{ env.PACKAGE_DIR }}

      - name: Setup Java 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: ${{ env.java_version }}
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
          cache: false

      # Verify the version matches pubspec.yaml
      - name: Verify package version
        run: |
          PUBSPEC_VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          if [ "$PUBSPEC_VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch: pubspec.yaml ($PUBSPEC_VERSION) != tag ($TAG_VERSION)"
            exit 1
          fi

      - name: Install dependencies
        run: dart pub get
          
      - name: Analyze
        run: dart analyze

      - name: Run tests
        run: dart test
  
      - name: Format check
        run: dart format --set-exit-if-changed --line-length=120 .
  
      - name: Check Publish Warnings
        run: dart pub publish --dry-run

      - name: Pub publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true
          force: false
